### ISSUE TITLE
latest Firefox TLS issues

### ISSUE THREAD

**Issue by DibyaTheXPFan** [MyTDT-Mysoft/DllCompat#11]
Do you have any fix ?

**Comment by MyTDT-Mysoft** [comment]
if thats about the TLS on dynamic loaded libraries... then thats what tls_deps.dll is for
one would put build a custom (per project) tls_deps.dll along kernel3x and add the libraries that require static linking (at program load) there...

**Comment by pachuco** [comment]
Duplicate of #6
