### ISSUE TITLE
[missing api] Xhip 8 rc1

### ISSUE THREAD

**Issue by pachuco** [MyTDT-Mysoft/DllCompat#3]
This one is a VST plugin.
kernel3x->GetThreadId()

http://xhip.net/alpha/

**Comment by MyTDT-Mysoft** [comment]
GetThreadId() got implemented....

**Comment by pachuco** [comment]
https://my.mixtape.moe/rysvnb.PNG

Not sure why this error happens, but the dll works correctly.
Same would happen if I returned 0 from GetThreadId()

Error does not appear in win7, either by wrapper dll or natively, so I think it's something else.

**Comment by pachuco** [comment]
Stale issue.
